version: '3.8'

services:
  bot:
    build: .
    container_name: tg_bot
    restart: always
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - SSH_HOST=${SSH_HOST}
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_PASSWORD=${SSH_PASSWORD}
      - DB_SERVER=${DB_SERVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - USER_1C=${USER_1C}
      - USER_1C_PASSWORD=${USER_1C_PASSWORD}
      - RCLONE_REMOTE=${RCLONE_REMOTE}
      - RCLONE_PATH=${RCLONE_PATH}
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup tg_bot
    restart: always 